"""create authorized_users table

Revision ID: a6bc77414d12
Revises: f40f4ea80ce2
Create Date: 2026-08-29 11:22:56.309747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6bc77414d12"
down_revision: str | Sequence[str] | None = "f40f4ea80ce2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authorized_users",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("telegram_user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("authorized_users")
    # ### end Alembic commands ###
