"""create screen_time table

Revision ID: f40f4ea80ce2
Revises: 27e0dd4e3c0c
Create Date: 2026-08-29 07:23:37.255676

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f40f4ea80ce2"
down_revision: str | Sequence[str] | None = "27e0dd4e3c0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screen_time",
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("total_minutes", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("entry_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("screen_time")
    # ### end Alembic commands ###
